trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Hello from Azure Pipelines with Ubuntu agent!"
      mkdir -p myfolder
      echo "hello world" > myfolder/hello.txt
      cat myfolder/hello.txt
    displayName: "Hello World"